<#
deploy_create_secret.ps1

Simple PowerShell helper to create a `secret_config.php` locally and upload it to a remote server
via scp/ssh. This is intended to be run from a trusted machine (your admin machine / CI runner).

Requirements:
- OpenSSH client (ssh & scp) must be available in PATH on Windows (Windows 10+ includes optional OpenSSH client)
- SSH key auth is recommended. If you use password auth, scp will prompt for password.

Usage examples:
PS> .\deploy_create_secret.ps1 -RemoteHost "git.example.com" -RemoteUser "www" -RemotePath "/var/www/cek-lokasi-client" -GoogleApiKey "PASTE_KEY"

Parameters:
-RemoteHost    : Remote host or IP
-RemoteUser    : SSH username
-RemotePath    : Destination directory on remote (where secret_config.php will be placed)
-Port          : SSH port (default 22)
-GoogleApiKey  : GOOGLE_MAPS_API_KEY value to write
-AllowedOrigins: optional comma-separated ALLOWED_ORIGINS
-ClientToken   : optional static CLIENT_TOKEN
-UseSudo       : switch - if set, the script will attempt to move the uploaded file to destination using sudo

Security note: Do NOT commit the generated `secret_config.php` into your repository. This script uploads it
directly to the remote host and removes the local temp file afterwards.
#>

param(
    [Parameter(Mandatory=$true)] [string] $RemoteHost,
    [Parameter(Mandatory=$true)] [string] $RemoteUser,
    [Parameter(Mandatory=$true)] [string] $RemotePath,
    [int] $Port = 22,
    [Parameter(Mandatory=$true)] [string] $GoogleApiKey,
    [string] $AllowedOrigins = '',
    [string] $ClientToken = '',
    [switch] $UseSudo
)

function Assert-HasCommand($name) {
    if (-not (Get-Command $name -ErrorAction SilentlyContinue)) {
        Write-Error "Required command '$name' not found in PATH. Please install OpenSSH client or ensure '$name' is available."
        exit 2
    }
}

Assert-HasCommand -name 'ssh'
Assert-HasCommand -name 'scp'

$tmp = Join-Path $env:TEMP ([System.Guid]::NewGuid().ToString() + '_secret_config.php')

$contents = "<?php`n"
$contents += "// Generated by deploy_create_secret.ps1 - keep this file OUTSIDE version control`n"
$contents += "`$GOOGLE_MAPS_API_KEY = '" + ($GoogleApiKey -replace "'","\\'") + "';`n"
if ($AllowedOrigins -ne '') {
    $contents += "`$ALLOWED_ORIGINS = '" + ($AllowedOrigins -replace "'","\\'") + "';`n"
}
if ($ClientToken -ne '') {
    $contents += "`$CLIENT_TOKEN = '" + ($ClientToken -replace "'","\\'") + "';`n"
}

Set-Content -Path $tmp -Value $contents -Encoding UTF8
Write-Host "Created temporary secret file: $tmp"

# Ensure remote dir exists
$mkdirCmd = "mkdir -p `"$RemotePath`""
Write-Host "Creating remote directory (if needed): $RemotePath"
$sshMk = & ssh -p $Port "$RemoteUser@$RemoteHost" $mkdirCmd 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Warning "Remote mkdir returned non-zero exit code: $sshMk"
}

# Upload with scp
$remoteTargetTemp = "/tmp/secret_config_$(Get-Random).php"
Write-Host "Uploading temp file to $RemoteHost:$remoteTargetTemp ..."
& scp -P $Port $tmp "$RemoteUser@$RemoteHost:$remoteTargetTemp"
if ($LASTEXITCODE -ne 0) {
    Write-Error "scp failed. Aborting and removing local temp file."
    Remove-Item -Force $tmp
    exit 3
}

if ($UseSudo) {
    Write-Host "Moving file to destination with sudo (you will be prompted for password if required)..."
    $moveCmd = "sudo mv `"$remoteTargetTemp`" `"$RemotePath/secret_config.php`" && sudo chown root:root `"$RemotePath/secret_config.php`" && sudo chmod 640 `"$RemotePath/secret_config.php`""
    $sshMove = & ssh -p $Port "$RemoteUser@$RemoteHost" $moveCmd 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Remote move (sudo) failed: $sshMove"
        Remove-Item -Force $tmp
        exit 4
    }
} else {
    Write-Host "Moving file to destination without sudo..."
    $moveCmd = "mv `"$remoteTargetTemp`" `"$RemotePath/secret_config.php`" && chown $(whoami) `"$RemotePath/secret_config.php`" || true && chmod 640 `"$RemotePath/secret_config.php`" || true"
    # Note: whoami on remote may differ; we'll run the command as the SSH user
    $sshMove = & ssh -p $Port "$RemoteUser@$RemoteHost" $moveCmd 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Warning "Remote move returned non-zero exit code: $sshMove"
        Write-Host "You may need to move the file manually on the server: $remoteTargetTemp -> $RemotePath/secret_config.php"
    }
}

Write-Host "Upload complete. Removing local temp file."
Remove-Item -Force $tmp

Write-Host "Done. secret_config.php should be at: $RemotePath/secret_config.php on $RemoteHost"

exit 0
